### ISSUE TITLE
[Feature]: iceberg v2 table  orphan file clean  trigger 

### ISSUE THREAD

**Issue by celltobig** [apache/amoro#1925]
### Description

I want  a iceberg table  of orphan file clean  , table expire snapshots,
has  table  property trigger ,not set time trigger

### Use case/motivation

<img width="1251" alt="image" src="https://github.com/NetEase/amoro/assets/4598224/7a1c9880-ad5a-440a-8035-9a7195380cf2">
<img width="1164" alt="image" src="https://github.com/NetEase/amoro/assets/4598224/742b0bab-e38f-4ff4-990e-6cac06327090">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
Thank you for raising this issue. This logic has already been extracted, and there will be a dedicated class responsible for snapshot expiration and orphan file cleaning in the future. Please refer to https://github.com/NetEase/amoro/pull/1916

**Comment by baiyangtx** [comment]
Would it be more reasonable to trigger it through a web page or some command-line method? Using the table property doesn't seem like a good approach.

**Comment by wangtaohz** [comment]
For the expiring snapshots and cleaning orphan files service, I think there should be two types of triggers: 
- a manual trigger for a single execution
- a automatic trigger for periodic executions

For the single manual trigger, it is suitable to be completed through a web UI (such as a button) or the command-line(#1357), which has been in our roadmap.
For the periodic automatic trigger, it is suitable to be configured as a setting. Of course, we can make this configuration to be more user-friendly like setting a timer on the web UI, but in the short term, I think it is feasible to configure it as a table property, like what we have done on the trigger of self-optimizing.

The goal of this issue is more focused on improving the periodic automatic trigger, and it doesn't conflict with the feature in #1357.

**Comment by baiyangtx** [comment]
How about implement in Spark SQL first, so that we can use it on Terminal SQL ?

**Comment by wangtaohz** [comment]
> How about implement in Spark SQL first, so that we can use it on Terminal SQL ?

AFAIK, Iceberg has already supported cleaning orphan files by calling spark Procedure, [remove_orphan_files](https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files) .

**Comment by baiyangtx** [comment]
> > How about implement in Spark SQL first, so that we can use it on Terminal SQL ?
> 
> AFAIK, Iceberg has already supported cleaning orphan files by calling spark Procedure, [remove_orphan_files](https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files) .

@celltobig Can this approach meet your needs?
