### ISSUE TITLE
isMinorNecessary() doesn't account for posDeleteFiles

### ISSUE THREAD

**Issue by deniskuzZ** [apache/amoro#2807]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

smallFileCount in isMinorNecessary()

### How should we improve?

int smallFileCount = fragmentFileCount + equalityDeleteFileCount + posDeleteFileCount;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@deniskuzZ Thank you for propose the issue.

The `posDeleteFileCount` not included in `isMinorNecessary` method is expected.

(Assume target size is 128m)

`Minor` mainly include the follow two:
- Merge data files smaller than 16m
- Convert eq delete associated with files larger than 16m

`Major` mainly include the follow two:
- Merge data files in 16～112m
- Merge data files larger than 112m and pos files to generate new data files.

**Comment by deniskuzZ** [comment]
@zhongqishang, thanks for checking! 
Positional deletes are very expensive for read operations, so many customers with read-heavy use cases migrate to COW mode. Without proper caching on the executor side situation is even worse. In Spark Iceberg there is `RewritePositionDeleteFilesSparkAction` specifically created for that. 
It's common for transactional workflows to generate multiple small delete files that cause the perf penalties unless compacted.

**Comment by zhongqishang** [comment]
@deniskuzZ Yes, I agree the point.

Amoro provides the ability to continuously merge data files and delete files, including position delete file.

In Amoro, rewrite position delete file needs to trigger rules. Rewirte data file and position delete file will be performed under the following two conditions.

- The number of data files smaller than 16m + eq delete file count exceeds `self-optimizing.minor.trigger.file-count`[1]
- The position delete record count associated with a data file exceeding 16m is greater than 10% of the data file record count (self-optimizing.major.trigger.duplicate-ratio)[2]

The triggering rule is to reduce the rewrite amplification problem caused by continuous data writing. Maybe a periodic rewrite all file (`self-optimizing.full.rewrite-all-files`)might help you[3].

[1] : https://github.com/apache/amoro/blob/master/amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/plan/CommonPartitionEvaluator.java#L321
[2] : https://github.com/apache/amoro/blob/master/amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/plan/CommonPartitionEvaluator.java#L198-L214
[3] : https://amoro.apache.org/docs/0.6.1/configurations/#data-cleaning-configurations

**Comment by zhongqishang** [comment]
> still think that it would be useful for minor compaction to have a threshold based on pos delete files count (why eq deletes should be any different?). 

`minor` mainly does two things, 
1. Merge files smaller than 16m
2. Convert eq delete file to position delete file

So when a 128m data file is associated with an eq delete file, the eq delete file will be convert into a position delete through `minor`.
If rewrite position in `minor`, the file will be read and written very frequently, which is also very expensive.

In short, there is rewrite position file, which is in the `major` stage. In order to reduce the cost of reading and writing, a threshold is added (`self-optimizing.major.trigger.duplicate-ratio`).
